[package]
name = "fui_controls"
version = "0.1.0"
authors = ["Marek G <no@mail.com>"]
edition = "2018"

[dependencies]
drawing = { path = "../../rust-drawing/drawing", version = "*" }
fui = { path = "../fui", version = "*" }
fui_macros = { path = "../../rust-fui/fui_macros", version = "*" }
euclid = "0.21"
typed-builder = "0.7"
typemap = "0.3"
