[package]
name = "fui_macros"
version = "0.1.0"
authors = ["Marek G <marek@nomail.com>"]
edition = "2018"

[dependencies]
fui_macros_impl = { path = "../fui_macros_impl" }
proc-macro-hack = "0.5"
typed-builder = "0.7"
typemap = "0.3"