[package]
name = "fui_app"
version = "0.1.0"
authors = ["Marek G <no@mail.com>"]
edition = "2018"

[dependencies]
drawing = { path = "../../rust-drawing/drawing", version = "*" }
drawing_gl = { path = "../../rust-drawing/drawing_gl", version = "*" }
fui = { path = "../fui", version = "*" }
anyhow = "1.0"
winit = "0.22"
shared_library = "0.1"
find_folder = "0.3"
typed-builder = "0.7"
typemap = "0.3"
cpu-time = "1.0"