[package]
name = "fui_examples"
version = "0.1.0"
authors = ["Marek G <no@mail.com>"]

[dependencies]
fui = { path = "../../rust-fui/fui", version = "*" }
winit = "*"

[[bin]]
name = "example1"
path = "src/example1.rs"
