[package]
name = "fui_examples"
version = "0.1.0"
authors = ["Marek G <no@mail.com>"]

[dependencies]
fui = { path = "../../rust-fui/fui", version = "*" }
fui_controls = { path = "../../rust-fui/fui_controls", version = "*" }
fui_macros = { path = "../../rust-fui/fui_macros", version = "*" }
winit = "0.20.0-alpha4"
failure = "0.1"
time = "0.1"
typed-builder = "0.3"
typemap = "0.3"

fui_controls_media = { path = "../../rust-fui/fui_controls_media", version = "*", optional = true }

[features]
video = ["fui_controls_media"]

[[bin]]
name = "example1_button"
path = "src/example1_button.rs"

[[bin]]
name = "example2_multiwindow"
path = "src/example2_multiwindow.rs"

[[bin]]
name = "example3_layout"
path = "src/example3_layout.rs"

[[bin]]
name = "example4_list"
path = "src/example4_list.rs"

[[bin]]
name = "example5_video"
path = "src/example5_video.rs"
required-features = ["video"]
