[package]
name = "fui_examples"
version = "0.1.0"
authors = ["Marek G <no@mail.com>"]

[dependencies]
fui = { path = "../../rust-fui/fui", version = "*" }
fui_macros = { path = "../../rust-fui/fui_macros", version = "*" }
winit = "*"
#winit = { git = "https://github.com/marek-g/winit" }
failure = "*"
time = "*"
typed-builder = "0.3"
typemap = "0.3"

fui_video = { path = "../../rust-fui/fui_video", version = "*", optional = true }

[features]
video = ["fui_video"]

[[bin]]
name = "example1_button"
path = "src/example1_button.rs"

[[bin]]
name = "example2_multiwindow"
path = "src/example2_multiwindow.rs"

[[bin]]
name = "example3_video"
path = "src/example3_video.rs"
required-features = ["video"]
