[package]
name = "fui_controls_media"
version = "0.1.0"
authors = ["Marek G <no@mail.com>"]
edition = "2018"

[dependencies]
drawing = { path = "../../rust-drawing/drawing", version = "*" }
drawing_gl = { path = "../../rust-drawing/drawing_gl", version = "*" }
fui_core = { path = "../fui_core", version = "*" }
fui_app = { path = "../../rust-fui/fui_app", version = "*" }
gstreamer_media = { path = "../../rust-media/gstreamer_media", version = "*" }
anyhow = "1.0"
gstreamer = "0.16"
gstreamer-sys = "0.9"
gstreamer-app = "0.16"
gstreamer-video = "0.16"
gstreamer-video-sys = "0.9"
glib = "0.10"
glutin = "0.24"
gl = "0.14"
winit = "0.22"
time = "0.2"
