[package]
name = "fui_macros_impl"
version = "0.1.0"
authors = ["Marek G <marek@nomail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features=["full"] }
quote = "1"
proc-macro-hack = "0.5"
proc-macro2 = "1"
