[package]
name = "fui_core"
version = "0.1.0"
authors = ["Marek G <no@mail.com>"]
edition = "2018"

[dependencies]
drawing = { path = "../../rust-drawing/drawing", version = "*" }
anyhow = "1.0"
typed-builder = "0.7"
typemap = "0.3"
